- label: Actuarial
  journals: 'ASTIN Bulletin, Insurance: Mathematics and Economics, Annals of Actuarial Science, North American Actuarial Journal, European Actuarial Journal'
- label: Finance
  journals: 'Quantitative Finance, Mathematical Finance, Finance &amp; Stochastics'
- label: OR
  journals: Mathematics of Operations Research
- label: Probability
  journals: 'Statistics &amp; Probability Letters'
- label: Economics
  journals: Economic Modelling
