- label: Actuarial
  journals: 'Insurance: Mathematics and Economics, ASTIN Bulletin, North American Actuarial Journal, European Actuarial Journal, Annals of Actuarial Science'
- label: Finance
  journals: 'Mathematical Finance, Finance &amp; Stochastics, Quantitative Finance'
- label: OR
  journals: Operations Research, Mathematics of Operations Research, European Journal of Operational Research
- label: Probability
  journals: 'Statistics &amp; Probability Letters'
- label: Economics
  journals: Economic Modelling
